# Generated by Django 5.2.2 on 2025-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('google', 'Google')], default='google', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
