# Generated by Django 5.2.2 on 2025-06-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admin',
            new_name='created_by',
        ),
    ]
