# Generated by Django 5.2.2 on 2025-06-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_admin_group_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'SyncGroup', 'verbose_name_plural': 'SyncGroups'},
        ),
    ]
